// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  title = 'angular-seo';
  footerUrl = 'https://www.ganatan.com/';
  footerLink = 'www.ganatan.com';

  constructor(
    @Inject(PLATFORM_ID) private platformId: object) {
  }

  ngOnInit(): void {

    if (isPlatformBrowser(this.platformId)) {
      const navMain = document.getElementById('navbarCollapse');
      if (navMain) {
        navMain.onclick = function onClick() {
          if (navMain) {
            navMain.classList.remove("show");
          }
        }
      }
    }
  } 

}
<header class="navbar navbar-expand-md navbar-dark fixed-top nga-navbar">
  <nav class="container" aria-label="Main navigation">
    <a routerLink="/" class="navbar-brand" alt="Accueil" aria-label="Ganatan">
      <img src="./assets/params/images/logo/ganatan-logo.png" srcset="./assets/params/images/logo/ganatan-logo.png,
      ./assets/params/images/logo/ganatan-logo@2x.png 2x" width="25" height="25" alt="Logo Ganatan">
      <span class="nga-logo mx-1">ganatan</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" routerLink="/">
            <i class="fas fa-home me-1"></i>Home</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" routerLink="/about">
            <i class="far fa-question-circle me-1"></i>About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" routerLink="/contact">
            <i class="fas fa-envelope me-1"></i>Contact</a>
        </li>
      </ul>
      <form class="d-flex">
        <button type="button" class="btn btn-sm nga-btn-navbar me-2" routerLink="/signup"><i
            class="fas fa-user-plus me-2"></i>Sign up</button>
        <button type="button" class="btn btn-sm btn-outline-light me-2" routerLink="/login"><i
            class="fas fa-sign-in-alt me-2"></i>Login</button>
      </form>
    </div>
  </nav>
</header>

<main>
  <router-outlet></router-outlet>
</main>

<footer class="nga-footer">
  <div class="py-3 text-center" style="background-color: black;">
    <div class="container">
      <a href="https://www.ganatan.com/"> www.ganatan.com</a>
    </div>
  </div>
</footer>

// react/src/app/app.js

import React from 'react';
import { Link, NavLink } from "react-router-dom";

import AppRouting from './app-routing';
import ganatanLogo from '../assets/params/images/logo/ganatan-logo.png';

import './app.css';

import 'bootstrap/dist/js/bootstrap.bundle.min.js'

class App extends React.Component {

  constructor(props) {
    super(props);
    this.title = 'react-seo';
    this.footerUrl = 'https://www.ganatan.com';
    this.footerLink = 'www.ganatan.com';
  }

  componentDidMount() {
    const navMain = document.getElementById('navbarCollapse');
    if (navMain) {
      navMain.onclick = function onclick() {
        if (navMain) {
          navMain.classList.remove("show");
        }
      }
    }
  }

  render() {
    const style = {
      backgroundColor: 'black',
    };

    return (

      <div className="app">

        <header className="navbar navbar-expand-md navbar-dark fixed-top nga-navbar">
          <nav className="container" aria-label="Main navigation">
            <NavLink className="navbar-brand" to="/">
              <img src={ganatanLogo} width="25" height="25" alt="Ganatan Logo" />
              <span className="nga-logo mx-1">ganatan</span>
            </NavLink>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarCollapse">
              <ul className="navbar-nav mx-auto">
                <li className="nav-item">
                  <NavLink className="nav-link" to="/"><i className="fas fa-home me-1"></i>Home</NavLink>
                </li>
              </ul>
              <ul className="navbar-nav me-auto">
                <li className="nav-item">
                  <NavLink className="nav-link" to="/about"><i className="far fa-question-circle me-1"></i>About</NavLink>
                </li>
                <li className="nav-item">
                  <NavLink className="nav-link" to="/contact"><i className="fas fa-envelope me-1"></i>Contact</NavLink>
                </li>
              </ul>

              <form className="d-flex">
                <Link to="/signup">
                  <button type="button" className="btn btn-sm nga-btn-navbar me-2"><i className="fas fa-user-plus me-2"></i>Sign
                    up</button>
                </Link>
                <Link to="/login">
                  <button type="button" className="btn btn-sm btn-outline-light me-2"><i
                    className="fas fa-sign-in-alt me-2"></i>Login</button>
                </Link>
              </form>

            </div>
          </nav>
        </header>
        <main>
          <AppRouting />
        </main>
        <footer className="nga-footer">
          <div className="py-3 text-center" style={style}>
            <div className="container">
              <a href="{ this.footerUrl }">{this.footerLink}</a>
            </div>
          </div>
        </footer>
      </div>

    )
  }

}

export default App;
